<?php

namespace SaasReady\Database\Migrations;

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use SaasReady\Models\Currency;

return new class () extends Migration {
    public function up(): void
    {
        $currencies = array_map(function (array $currency) {
            return [
                ...$currency,
                'uuid' => Str::orderedUuid(),
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }, [
            [
                'code' => 'AUD',
                'name' => 'Australian Dollar',
                'symbol' => 'AU$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'BND',
                'name' => 'Brunei Dollar',
                'symbol' => 'B$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'CAD',
                'name' => 'Canadian Dollar',
                'symbol' => 'CA$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'CHF',
                'name' => 'Swiss Franc',
                'symbol' => 'Fr',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'CNY',
                'name' => 'Chinese Yuan',
                'symbol' => '¥',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'EUR',
                'name' => 'Euro',
                'symbol' => '€',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => true,
            ],
            [
                'code' => 'GBP',
                'name' => 'British Pound',
                'symbol' => '£',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'HKD',
                'name' => 'Hong Kong Dollar',
                'symbol' => 'HK$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'IDR',
                'name' => 'Indonesian Rupiah',
                'symbol' => 'Rp',
                'decimals' => 0,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => true,
            ],
            [
                'code' => 'INR',
                'name' => 'Indian Rupee',
                'symbol' => '₹',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'JPY',
                'name' => 'Japanese Yen',
                'symbol' => '¥',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'KHR',
                'name' => 'Cambodian Riel',
                'symbol' => '៛',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'KRW',
                'name' => 'South Korean Won',
                'symbol' => '₩',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'LAK',
                'name' => 'Lao Kip',
                'symbol' => '₭',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'MMK',
                'name' => 'Burmese Kyat',
                'symbol' => 'Ks',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'MOP',
                'name' => 'Macanese Pataca',
                'symbol' => 'P',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'MYR',
                'name' => 'Malaysian Ringgit',
                'symbol' => 'RM',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'PHP',
                'name' => 'Philippine Peso',
                'symbol' => '₱',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'RUB',
                'name' => 'Russian Ruble',
                'symbol' => '₽',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'SGD',
                'name' => 'Singapore Dollar',
                'symbol' => 'S$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'THB',
                'name' => 'Thai Baht',
                'symbol' => '฿',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'USD',
                'name' => 'United States Dollar',
                'symbol' => '$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'VND',
                'name' => 'Vietnamese Đồng',
                'symbol' => '₫',
                'decimals' => 0,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'TWD',
                'name' => 'New Taiwan Dollar',
                'symbol' => 'NT$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'ARS',
                'name' => 'Argentine Peso',
                'symbol' => '$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'BWP',
                'name' => 'Botswanan Pula',
                'symbol' => 'P',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'BGN',
                'name' => 'Bulgarian Lev',
                'symbol' => 'Лв.',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'XOF',
                'name' => 'West African CFA Franc',
                'symbol' => 'CFA',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'CLP',
                'name' => 'Chilean Peso',
                'symbol' => '$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'COP',
                'name' => 'Colombian Peso',
                'symbol' => '$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'CRC',
                'name' => 'Costa Rican Colón',
                'symbol' => '₡',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'HRK',
                'name' => 'Croatian Kuna',
                'symbol' => 'kn',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'CZK',
                'name' => 'Czech Koruna',
                'symbol' => 'Kč',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'DKK',
                'name' => 'Danish Krone',
                'symbol' => 'Kr.',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'EGP',
                'name' => 'Egyptian Pound',
                'symbol' => 'E£',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'GEL',
                'name' => 'Georgian Lari',
                'symbol' => 'GEL',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'GHS',
                'name' => 'Ghanaian Cedi',
                'symbol' => 'GH¢',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'HUF',
                'name' => 'Hungarian Forint',
                'symbol' => 'Ft',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'KES',
                'name' => 'Kenyan Shilling',
                'symbol' => 'Ksh',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'MXN',
                'name' => 'Mexican Peso',
                'symbol' => 'Mex$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'MAD',
                'name' => 'Moroccan Dirham',
                'symbol' => 'MAD',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'ILS',
                'name' => 'Israeli New Shekel',
                'symbol' => '₪',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'NGN',
                'name' => 'Nigerian Naira',
                'symbol' => '₦',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'NPR',
                'name' => 'Nepalese Rupee',
                'symbol' => 'Re.',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'NZD',
                'name' => 'New Zealand Dollar',
                'symbol' => '$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'NOK',
                'name' => 'Norwegian Krone',
                'symbol' => 'kr',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'PEN',
                'name' => 'Peruvian sol',
                'symbol' => 'S/',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'RON',
                'name' => 'Romanian Leu',
                'symbol' => 'lei',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'ZAR',
                'name' => 'South African Rand',
                'symbol' => 'R',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'LKR',
                'name' => 'Sri Lankan Rupee',
                'symbol' => 'Rs',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'SEK',
                'name' => 'Swedish Krona',
                'symbol' => 'kr',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'TZS',
                'name' => 'Tanzanian Shilling',
                'symbol' => 'TSh',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'TRY',
                'name' => 'Turkish lira',
                'symbol' => '₺',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'AED',
                'name' => 'United Arab Emirates Dirham',
                'symbol' => 'د.إ',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'UGX',
                'name' => 'Ugandan Shilling',
                'symbol' => 'USh',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'UAH',
                'name' => 'Ukrainian hryvnia',
                'symbol' => '₴',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'UYU',
                'name' => 'Uruguayan Peso',
                'symbol' => '$U',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'ZMW',
                'name' => 'Zambian Kwacha',
                'symbol' => 'ZK',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'KWD',
                'name' => 'Kuwait Dinar',
                'symbol' => 'د.ك',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'OMR',
                'name' => 'Omani Rial',
                'symbol' => 'ر.ع.',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'PLN',
                'name' => 'Polish Złoty',
                'symbol' => 'zł',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'QAR',
                'name' => 'Qatari Rial',
                'symbol' => 'ر.ق',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'SAR',
                'name' => 'Saudi Riyal',
                'symbol' => 'ر.س',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'BHD',
                'name' => 'Bahraini Dinar',
                'symbol' => '.د.ب',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'AFN',
                'name' => 'Afghan Afghani',
                'symbol' => '؋',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'ALL',
                'name' => 'Albanian Lek',
                'symbol' => 'L',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'DZD',
                'name' => 'Algerian Dinar',
                'symbol' => 'دج',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'AOA',
                'name' => 'Angolan Kwanza',
                'symbol' => 'Kz',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'XCD',
                'name' => 'Eastern Caribbean Dollar',
                'symbol' => '$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'AMD',
                'name' => 'Armenian Dram',
                'symbol' => '֏',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'AWG',
                'name' => 'Aruban Florin',
                'symbol' => 'ƒ',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'AZN',
                'name' => 'Azerbaijani Manat',
                'symbol' => '₼',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'BSD',
                'name' => 'Bahamian Dollar',
                'symbol' => 'B$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'BDT',
                'name' => 'Bangladeshi Taka',
                'symbol' => '৳',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'BBD',
                'name' => 'Barbados Dollar',
                'symbol' => 'Bds$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'BYN',
                'name' => 'Belarusian Ruble',
                'symbol' => 'Br',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'BZD',
                'name' => 'Belize Dollar',
                'symbol' => '$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'BMD',
                'name' => 'Bermudian Dollar',
                'symbol' => '$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'BTN',
                'name' => 'Bhutanese Ngultrum',
                'symbol' => 'Nu.',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'BOB',
                'name' => 'Bolivian Boliviano',
                'symbol' => 'Bs',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'BAM',
                'name' => 'Bosnia and Herzegovina Convertible Mark',
                'symbol' => 'KM',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'BRL',
                'name' => 'Brazilian Real',
                'symbol' => 'R$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'BIF',
                'name' => 'Burundian Franc',
                'symbol' => 'FBu',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'XAF',
                'name' => 'Central African CFA Franc',
                'symbol' => 'FCFA',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'CVE',
                'name' => 'Cape Verdean Escudo',
                'symbol' => 'Esc',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'KYD',
                'name' => 'Cayman Islands Dollar',
                'symbol' => '$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'KMF',
                'name' => 'Comorian Franc',
                'symbol' => 'CF',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'CDF',
                'name' => 'Congolese Franc',
                'symbol' => 'FC',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'CUP',
                'name' => 'Cuban Peso',
                'symbol' => '₱',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'ANG',
                'name' => 'Netherlands Antillean Guilder',
                'symbol' => 'ƒ',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'DJF',
                'name' => 'Djiboutian Franc',
                'symbol' => 'Fdj',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'DOP',
                'name' => 'Dominican Peso',
                'symbol' => 'RD$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'SVC',
                'name' => 'Salvadoran Colon',
                'symbol' => '₡',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'ERN',
                'name' => 'Eritrean Nakfa',
                'symbol' => 'Nfk',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'ETB',
                'name' => 'Ethiopian Birr',
                'symbol' => 'Br',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'FKP',
                'name' => 'Falkland Islands Pound',
                'symbol' => '£',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'FJD',
                'name' => 'Fijian Dollar',
                'symbol' => 'FJ$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'XPF',
                'name' => 'CFP Franc',
                'symbol' => '₣',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'GMD',
                'name' => 'Gambian Dalasi',
                'symbol' => 'D',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'GIP',
                'name' => 'Gibraltar Pound',
                'symbol' => '£',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'GTQ',
                'name' => 'Guatemalan Quetzal',
                'symbol' => 'Q',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'GNF',
                'name' => 'Guinean Franc',
                'symbol' => 'FG',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'GYD',
                'name' => 'Guyanese Dollar',
                'symbol' => 'GY$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'HTG',
                'name' => 'Haitian Gourde',
                'symbol' => 'G',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'HNL',
                'name' => 'Honduran Lempira',
                'symbol' => 'L',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'ISK',
                'name' => 'Icelandic Krona',
                'symbol' => 'kr',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'IRR',
                'name' => 'Iranian Rial',
                'symbol' => '﷼',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'IQD',
                'name' => 'Iraqi Dinar',
                'symbol' => 'ع.د',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'JMD',
                'name' => 'Jamaican Dollar',
                'symbol' => '$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'JOD',
                'name' => 'Jordanian Dinar',
                'symbol' => 'د.ا',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'KZT',
                'name' => 'Kazakhstani Tenge',
                'symbol' => '₸',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'KPW',
                'name' => 'North Korean Won',
                'symbol' => '₩',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'KGS',
                'name' => 'Kyrgyzstani Som',
                'symbol' => 'Лв',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'LBP',
                'name' => 'Lebanese Pound',
                'symbol' => 'ل.ل.',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'LSL',
                'name' => 'Lesotho Loti',
                'symbol' => 'L',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'LRD',
                'name' => 'Liberian Dollar',
                'symbol' => 'L$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'LYD',
                'name' => 'Libyan Dinar',
                'symbol' => 'ل.د',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'MKD',
                'name' => 'Macedonian Denar',
                'symbol' => 'Ден',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'MGA',
                'name' => 'Malagasy Ariary',
                'symbol' => 'Ar',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'MWK',
                'name' => 'Malawian Kwacha',
                'symbol' => 'MK',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'MVR',
                'name' => 'Maldivian Rufiyaa',
                'symbol' => '.ރ',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'MRO',
                'name' => 'Mauritanian Ouguiya',
                'symbol' => 'UM',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'MUR',
                'name' => 'Mauritian Rupee',
                'symbol' => '₨',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'MDL',
                'name' => 'Moldovan Leu',
                'symbol' => 'L',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'MNT',
                'name' => 'Mongolian Togrog',
                'symbol' => '₮',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'MZN',
                'name' => 'Mozambican Metical',
                'symbol' => 'MT',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'NAD',
                'name' => 'Namibian Dollar',
                'symbol' => 'N$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'NIO',
                'name' => 'Nicaraguan Cordoba',
                'symbol' => 'C$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'PKR',
                'name' => 'Pakistani Rupee',
                'symbol' => '₨',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'PAB',
                'name' => 'Panamanian Balboa',
                'symbol' => 'B/.',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'PGK',
                'name' => 'Papua New Guinean Kina',
                'symbol' => 'K',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'PYG',
                'name' => 'Paraguayan Guarani',
                'symbol' => '₲',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'RWF',
                'name' => 'Rwandan Franc',
                'symbol' => 'FRw',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'SHP',
                'name' => 'Saint Helena Pound',
                'symbol' => '£',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'WST',
                'name' => 'Samoan Tala',
                'symbol' => 'WS$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'STD',
                'name' => 'Sao Tome and Principe Dobra',
                'symbol' => 'Db',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'RSD',
                'name' => 'Serbian Dinar',
                'symbol' => 'din',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'SCR',
                'name' => 'Seychellois Rupee',
                'symbol' => '₨ /-',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'SLL',
                'name' => 'Sierra Leonean Leone',
                'symbol' => 'Le',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'SBD',
                'name' => 'Solomon Islands Dollar',
                'symbol' => 'Si$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'SOS',
                'name' => 'Somali Shilling',
                'symbol' => 'Sh.so.',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'SSP',
                'name' => 'South Sudanese Pound',
                'symbol' => '£',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'SDG',
                'name' => 'Sudanese Pound',
                'symbol' => 'ج.س.',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'SRD',
                'name' => 'Suriname Dollar',
                'symbol' => '$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'SZL',
                'name' => 'Swazi Lilangeni',
                'symbol' => 'E',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'SYP',
                'name' => 'Syrian Pound',
                'symbol' => '£S',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'TJS',
                'name' => 'Tajikistani Somoni',
                'symbol' => 'SM',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'TOP',
                'name' => 'Tongan Paʻanga',
                'symbol' => 'T$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'TTD',
                'name' => 'Trinidad and Tobago Dollar',
                'symbol' => 'TT$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'TND',
                'name' => 'Tunisian dinar',
                'symbol' => 'د.ت',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'TMT',
                'name' => 'Turkmenistani Manat',
                'symbol' => 'T',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'UZS',
                'name' => 'Uzbekistani soʻm',
                'symbol' => "so'm",
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'VUV',
                'name' => 'Vanuatu Vatu',
                'symbol' => 'VT',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'VEF',
                'name' => 'Venezuelan bolívar',
                'symbol' => 'Bs.S',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'YER',
                'name' => 'Yemeni Rial',
                'symbol' => '﷼',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
            [
                'code' => 'ZWL',
                'name' => 'Zimbabwean Dollar',
                'symbol' => '$',
                'decimals' => 2,
                'decimal_separator' => '.',
                'thousands_separator' => ',',
                'space_after_symbol' => false,
            ],
        ]);

        DB::table((new Currency())->getTable())
            ->insert($currencies);
    }

    public function down(): void
    {
        // 1 way
    }
};
