<?php

namespace SaasReady\Database\Migrations;

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use SaasReady\Models\Country;

return new class () extends Migration {
    public function up(): void
    {
        $countries = array_map(function (array $country) {
            return [
                ...$country,
                'uuid' => Str::orderedUuid(),
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }, [
            [
                'code' => 'AD',
                'name' => 'Andorra',
                'continent' => 'Europe',
                'dial_code' => '+376',
            ],
            [
                'code' => 'AE',
                'name' => 'United Arab Emirates',
                'continent' => 'Asia',
                'dial_code' => '+971',
            ],
            [
                'code' => 'AF',
                'name' => 'Afghanistan',
                'continent' => 'Asia',
                'dial_code' => '+93',
            ],
            [
                'code' => 'AG',
                'name' => 'Antigua and Barbuda',
                'continent' => 'North America',
                'dial_code' => '+1268',
            ],
            [
                'code' => 'AI',
                'name' => 'Anguilla',
                'continent' => 'North America',
                'dial_code' => '+1264',
            ],
            [
                'code' => 'AL',
                'name' => 'Albania',
                'continent' => 'Europe',
                'dial_code' => '+355',
            ],
            [
                'code' => 'AM',
                'name' => 'Armenia',
                'continent' => 'Asia',
                'dial_code' => '+374',
            ],
            [
                'code' => 'AO',
                'name' => 'Angola',
                'continent' => 'Africa',
                'dial_code' => '+244',
            ],
            [
                'code' => 'AQ',
                'name' => 'Antarctica',
                'continent' => 'Antarctica',
                'dial_code' => '+672',
            ],
            [
                'code' => 'AR',
                'name' => 'Argentina',
                'continent' => 'South America',
                'dial_code' => '+54',
            ],
            [
                'code' => 'AS',
                'name' => 'American Samoa',
                'continent' => 'Oceania',
                'dial_code' => '+1684',
            ],
            [
                'code' => 'AT',
                'name' => 'Austria',
                'continent' => 'Europe',
                'dial_code' => '+43',
            ],
            [
                'code' => 'AU',
                'name' => 'Australia',
                'continent' => 'Oceania',
                'dial_code' => '+61',
            ],
            [
                'code' => 'AW',
                'name' => 'Aruba',
                'continent' => 'North America',
                'dial_code' => '+297',
            ],
            [
                'code' => 'AX',
                'name' => 'Åland',
                'continent' => 'Europe',
                'dial_code' => '+358',
            ],
            [
                'code' => 'AZ',
                'name' => 'Azerbaijan',
                'continent' => 'Asia',
                'dial_code' => '+994',
            ],
            [
                'code' => 'BA',
                'name' => 'Bosnia and Herzegovina',
                'continent' => 'Europe',
                'dial_code' => '+387',
            ],
            [
                'code' => 'BB',
                'name' => 'Barbados',
                'continent' => 'North America',
                'dial_code' => '+1246',
            ],
            [
                'code' => 'BD',
                'name' => 'Bangladesh',
                'continent' => 'Asia',
                'dial_code' => '+880',
            ],
            [
                'code' => 'BE',
                'name' => 'Belgium',
                'continent' => 'Europe',
                'dial_code' => '+32',
            ],
            [
                'code' => 'BF',
                'name' => 'Burkina Faso',
                'continent' => 'Africa',
                'dial_code' => '+226',
            ],
            [
                'code' => 'BG',
                'name' => 'Bulgaria',
                'continent' => 'Europe',
                'dial_code' => '+359',
            ],
            [
                'code' => 'BH',
                'name' => 'Bahrain',
                'continent' => 'Asia',
                'dial_code' => '+973',
            ],
            [
                'code' => 'BI',
                'name' => 'Burundi',
                'continent' => 'Africa',
                'dial_code' => '+257',
            ],
            [
                'code' => 'BJ',
                'name' => 'Benin',
                'continent' => 'Africa',
                'dial_code' => '+229',
            ],
            [
                'code' => 'BL',
                'name' => 'Saint Barthélemy',
                'continent' => 'North America',
                'dial_code' => '+590',
            ],
            [
                'code' => 'BM',
                'name' => 'Bermuda',
                'continent' => 'North America',
                'dial_code' => '+1441',
            ],
            [
                'code' => 'BN',
                'name' => 'Brunei',
                'continent' => 'Asia',
                'dial_code' => '+673',
            ],
            [
                'code' => 'BO',
                'name' => 'Bolivia',
                'continent' => 'South America',
                'dial_code' => '+591',
            ],
            [
                'code' => 'BQ',
                'name' => 'Bonaire',
                'continent' => 'North America',
                'dial_code' => '+599',
            ],
            [
                'code' => 'BR',
                'name' => 'Brazil',
                'continent' => 'South America',
                'dial_code' => '+55',
            ],
            [
                'code' => 'BS',
                'name' => 'Bahamas',
                'continent' => 'North America',
                'dial_code' => '+1242',
            ],
            [
                'code' => 'BT',
                'name' => 'Bhutan',
                'continent' => 'Asia',
                'dial_code' => '+975',
            ],
            [
                'code' => 'BV',
                'name' => 'Bouvet Island',
                'continent' => 'Antarctica',
                'dial_code' => '+47',
            ],
            [
                'code' => 'BW',
                'name' => 'Botswana',
                'continent' => 'Africa',
                'dial_code' => '+267',
            ],
            [
                'code' => 'BY',
                'name' => 'Belarus',
                'continent' => 'Europe',
                'dial_code' => '+375',
            ],
            [
                'code' => 'BZ',
                'name' => 'Belize',
                'continent' => 'North America',
                'dial_code' => '+501',
            ],
            [
                'code' => 'CA',
                'name' => 'Canada',
                'continent' => 'North America',
                'dial_code' => '+1',
            ],
            [
                'code' => 'CC',
                'name' => 'Cocos (Keeling) Islands',
                'continent' => 'Asia',
                'dial_code' => '+61',
            ],
            [
                'code' => 'CD',
                'name' => 'Democratic Republic of the Congo',
                'continent' => 'Africa',
                'dial_code' => '+243',
            ],
            [
                'code' => 'CF',
                'name' => 'Central African Republic',
                'continent' => 'Africa',
                'dial_code' => '+236',
            ],
            [
                'code' => 'CG',
                'name' => 'Republic of the Congo',
                'continent' => 'Africa',
                'dial_code' => '+242',
            ],
            [
                'code' => 'CH',
                'name' => 'Switzerland',
                'continent' => 'Europe',
                'dial_code' => '+41',
            ],
            [
                'code' => 'CI',
                'name' => 'Ivory Coast',
                'continent' => 'Africa',
                'dial_code' => '+225',
            ],
            [
                'code' => 'CK',
                'name' => 'Cook Islands',
                'continent' => 'Oceania',
                'dial_code' => '+682',
            ],
            [
                'code' => 'CL',
                'name' => 'Chile',
                'continent' => 'South America',
                'dial_code' => '+56',
            ],
            [
                'code' => 'CM',
                'name' => 'Cameroon',
                'continent' => 'Africa',
                'dial_code' => '+237',
            ],
            [
                'code' => 'CN',
                'name' => 'China',
                'continent' => 'Asia',
                'dial_code' => '+86',
            ],
            [
                'code' => 'CO',
                'name' => 'Colombia',
                'continent' => 'South America',
                'dial_code' => '+57',
            ],
            [
                'code' => 'CR',
                'name' => 'Costa Rica',
                'continent' => 'North America',
                'dial_code' => '+506',
            ],
            [
                'code' => 'CU',
                'name' => 'Cuba',
                'continent' => 'North America',
                'dial_code' => '+53',
            ],
            [
                'code' => 'CV',
                'name' => 'Cape Verde',
                'continent' => 'Africa',
                'dial_code' => '+238',
            ],
            [
                'code' => 'CW',
                'name' => 'Curaçao',
                'continent' => 'North America',
                'dial_code' => '+599',
            ],
            [
                'code' => 'CX',
                'name' => 'Christmas Island',
                'continent' => 'Oceania',
                'dial_code' => '+61',
            ],
            [
                'code' => 'CY',
                'name' => 'Cyprus',
                'continent' => 'Europe',
                'dial_code' => '+357',
            ],
            [
                'code' => 'CZ',
                'name' => 'Czechia',
                'continent' => 'Europe',
                'dial_code' => '+420',
            ],
            [
                'code' => 'DE',
                'name' => 'Germany',
                'continent' => 'Europe',
                'dial_code' => '+49',
            ],
            [
                'code' => 'DJ',
                'name' => 'Djibouti',
                'continent' => 'Africa',
                'dial_code' => '+253',
            ],
            [
                'code' => 'DK',
                'name' => 'Denmark',
                'continent' => 'Europe',
                'dial_code' => '+45',
            ],
            [
                'code' => 'DM',
                'name' => 'Dominica',
                'continent' => 'North America',
                'dial_code' => '+1767',
            ],
            [
                'code' => 'DO',
                'name' => 'Dominican Republic',
                'continent' => 'North America',
                'dial_code' => '+1809',
            ],
            [
                'code' => 'DZ',
                'name' => 'Algeria',
                'continent' => 'Africa',
                'dial_code' => '+213',
            ],
            [
                'code' => 'EC',
                'name' => 'Ecuador',
                'continent' => 'South America',
                'dial_code' => '+593',
            ],
            [
                'code' => 'EE',
                'name' => 'Estonia',
                'continent' => 'Europe',
                'dial_code' => '+372',
            ],
            [
                'code' => 'EG',
                'name' => 'Egypt',
                'continent' => 'Africa',
                'dial_code' => '+20',
            ],
            [
                'code' => 'EH',
                'name' => 'Western Sahara',
                'continent' => 'Africa',
                'dial_code' => '+212',
            ],
            [
                'code' => 'ER',
                'name' => 'Eritrea',
                'continent' => 'Africa',
                'dial_code' => '+291',
            ],
            [
                'code' => 'ES',
                'name' => 'Spain',
                'continent' => 'Europe',
                'dial_code' => '+34',
            ],
            [
                'code' => 'ET',
                'name' => 'Ethiopia',
                'continent' => 'Africa',
                'dial_code' => '+251',
            ],
            [
                'code' => 'FI',
                'name' => 'Finland',
                'continent' => 'Europe',
                'dial_code' => '+358',
            ],
            [
                'code' => 'FJ',
                'name' => 'Fiji',
                'continent' => 'Oceania',
                'dial_code' => '+679',
            ],
            [
                'code' => 'FK',
                'name' => 'Falkland Islands',
                'continent' => 'South America',
                'dial_code' => '+500',
            ],
            [
                'code' => 'FM',
                'name' => 'Micronesia',
                'continent' => 'Oceania',
                'dial_code' => '+691',
            ],
            [
                'code' => 'FO',
                'name' => 'Faroe Islands',
                'continent' => 'Europe',
                'dial_code' => '+298',
            ],
            [
                'code' => 'FR',
                'name' => 'France',
                'continent' => 'Europe',
                'dial_code' => '+33',
            ],
            [
                'code' => 'GA',
                'name' => 'Gabon',
                'continent' => 'Africa',
                'dial_code' => '+241',
            ],
            [
                'code' => 'GB',
                'name' => 'United Kingdom',
                'continent' => 'Europe',
                'dial_code' => '+44',
            ],
            [
                'code' => 'GD',
                'name' => 'Grenada',
                'continent' => 'North America',
                'dial_code' => '+1473',
            ],
            [
                'code' => 'GE',
                'name' => 'Georgia',
                'continent' => 'Asia',
                'dial_code' => '+995',
            ],
            [
                'code' => 'GF',
                'name' => 'French Guiana',
                'continent' => 'South America',
                'dial_code' => '+594',
            ],
            [
                'code' => 'GG',
                'name' => 'Guernsey',
                'continent' => 'Europe',
                'dial_code' => '+44',
            ],
            [
                'code' => 'GH',
                'name' => 'Ghana',
                'continent' => 'Africa',
                'dial_code' => '+233',
            ],
            [
                'code' => 'GI',
                'name' => 'Gibraltar',
                'continent' => 'Europe',
                'dial_code' => '+350',
            ],
            [
                'code' => 'GL',
                'name' => 'Greenland',
                'continent' => 'North America',
                'dial_code' => '+299',
            ],
            [
                'code' => 'GM',
                'name' => 'Gambia',
                'continent' => 'Africa',
                'dial_code' => '+220',
            ],
            [
                'code' => 'GN',
                'name' => 'Guinea',
                'continent' => 'Africa',
                'dial_code' => '+224',
            ],
            [
                'code' => 'GP',
                'name' => 'Guadeloupe',
                'continent' => 'North America',
                'dial_code' => '+590',
            ],
            [
                'code' => 'GQ',
                'name' => 'Equatorial Guinea',
                'continent' => 'Africa',
                'dial_code' => '+240',
            ],
            [
                'code' => 'GR',
                'name' => 'Greece',
                'continent' => 'Europe',
                'dial_code' => '+30',
            ],
            [
                'code' => 'GS',
                'name' => 'South Georgia and the South Sandwich Islands',
                'continent' => 'Antarctica',
                'dial_code' => '+500',
            ],
            [
                'code' => 'GT',
                'name' => 'Guatemala',
                'continent' => 'North America',
                'dial_code' => '+502',
            ],
            [
                'code' => 'GU',
                'name' => 'Guam',
                'continent' => 'Oceania',
                'dial_code' => '+1671',
            ],
            [
                'code' => 'GW',
                'name' => 'Guinea-Bissau',
                'continent' => 'Africa',
                'dial_code' => '+245',
            ],
            [
                'code' => 'GY',
                'name' => 'Guyana',
                'continent' => 'South America',
                'dial_code' => '+592',
            ],
            [
                'code' => 'HK',
                'name' => 'Hong Kong',
                'continent' => 'Asia',
                'dial_code' => '+852',
            ],
            [
                'code' => 'HM',
                'name' => 'Heard Island and McDonald Islands',
                'continent' => 'Antarctica',
                'dial_code' => '+6723',
            ],
            [
                'code' => 'HN',
                'name' => 'Honduras',
                'continent' => 'North America',
                'dial_code' => '+504',
            ],
            [
                'code' => 'HR',
                'name' => 'Croatia',
                'continent' => 'Europe',
                'dial_code' => '+385',
            ],
            [
                'code' => 'HT',
                'name' => 'Haiti',
                'continent' => 'North America',
                'dial_code' => '+509',
            ],
            [
                'code' => 'HU',
                'name' => 'Hungary',
                'continent' => 'Europe',
                'dial_code' => '+36',
            ],
            [
                'code' => 'ID',
                'name' => 'Indonesia',
                'continent' => 'Asia',
                'dial_code' => '+62',
            ],
            [
                'code' => 'IE',
                'name' => 'Ireland',
                'continent' => 'Europe',
                'dial_code' => '+353',
            ],
            [
                'code' => 'IL',
                'name' => 'Israel',
                'continent' => 'Asia',
                'dial_code' => '+972',
            ],
            [
                'code' => 'IM',
                'name' => 'Isle of Man',
                'continent' => 'Europe',
                'dial_code' => '+44',
            ],
            [
                'code' => 'IN',
                'name' => 'India',
                'continent' => 'Asia',
                'dial_code' => '+91',
            ],
            [
                'code' => 'IO',
                'name' => 'British Indian Ocean Territory',
                'continent' => 'Asia',
                'dial_code' => '+246',
            ],
            [
                'code' => 'IQ',
                'name' => 'Iraq',
                'continent' => 'Asia',
                'dial_code' => '+964',
            ],
            [
                'code' => 'IR',
                'name' => 'Iran',
                'continent' => 'Asia',
                'dial_code' => '+98',
            ],
            [
                'code' => 'IS',
                'name' => 'Iceland',
                'continent' => 'Europe',
                'dial_code' => '+354',
            ],
            [
                'code' => 'IT',
                'name' => 'Italy',
                'continent' => 'Europe',
                'dial_code' => '+39',
            ],
            [
                'code' => 'JE',
                'name' => 'Jersey',
                'continent' => 'Europe',
                'dial_code' => '+44',
            ],
            [
                'code' => 'JM',
                'name' => 'Jamaica',
                'continent' => 'North America',
                'dial_code' => '+1876',
            ],
            [
                'code' => 'JO',
                'name' => 'Jordan',
                'continent' => 'Asia',
                'dial_code' => '+962',
            ],
            [
                'code' => 'JP',
                'name' => 'Japan',
                'continent' => 'Asia',
                'dial_code' => '+81',
            ],
            [
                'code' => 'KE',
                'name' => 'Kenya',
                'continent' => 'Africa',
                'dial_code' => '+254',
            ],
            [
                'code' => 'KG',
                'name' => 'Kyrgyzstan',
                'continent' => 'Asia',
                'dial_code' => '+996',
            ],
            [
                'code' => 'KH',
                'name' => 'Cambodia',
                'continent' => 'Asia',
                'dial_code' => '+855',
            ],
            [
                'code' => 'KI',
                'name' => 'Kiribati',
                'continent' => 'Oceania',
                'dial_code' => '+686',
            ],
            [
                'code' => 'KM',
                'name' => 'Comoros',
                'continent' => 'Africa',
                'dial_code' => '+269',
            ],
            [
                'code' => 'KN',
                'name' => 'Saint Kitts and Nevis',
                'continent' => 'North America',
                'dial_code' => '+1869',
            ],
            [
                'code' => 'KP',
                'name' => 'North Korea',
                'continent' => 'Asia',
                'dial_code' => '+850',
            ],
            [
                'code' => 'KR',
                'name' => 'South Korea',
                'continent' => 'Asia',
                'dial_code' => '+82',
            ],
            [
                'code' => 'KW',
                'name' => 'Kuwait',
                'continent' => 'Asia',
                'dial_code' => '+965',
            ],
            [
                'code' => 'KY',
                'name' => 'Cayman Islands',
                'continent' => 'North America',
                'dial_code' => '+1345',
            ],
            [
                'code' => 'KZ',
                'name' => 'Kazakhstan',
                'continent' => 'Asia',
                'dial_code' => '+7',
            ],
            [
                'code' => 'LA',
                'name' => 'Laos',
                'continent' => 'Asia',
                'dial_code' => '+856',
            ],
            [
                'code' => 'LB',
                'name' => 'Lebanon',
                'continent' => 'Asia',
                'dial_code' => '+961',
            ],
            [
                'code' => 'LC',
                'name' => 'Saint Lucia',
                'continent' => 'North America',
                'dial_code' => '+1758',
            ],
            [
                'code' => 'LI',
                'name' => 'Liechtenstein',
                'continent' => 'Europe',
                'dial_code' => '+423',
            ],
            [
                'code' => 'LK',
                'name' => 'Sri Lanka',
                'continent' => 'Asia',
                'dial_code' => '+94',
            ],
            [
                'code' => 'LR',
                'name' => 'Liberia',
                'continent' => 'Africa',
                'dial_code' => '+231',
            ],
            [
                'code' => 'LS',
                'name' => 'Lesotho',
                'continent' => 'Africa',
                'dial_code' => '+266',
            ],
            [
                'code' => 'LT',
                'name' => 'Lithuania',
                'continent' => 'Europe',
                'dial_code' => '+370',
            ],
            [
                'code' => 'LU',
                'name' => 'Luxembourg',
                'continent' => 'Europe',
                'dial_code' => '+352',
            ],
            [
                'code' => 'LV',
                'name' => 'Latvia',
                'continent' => 'Europe',
                'dial_code' => '+371',
            ],
            [
                'code' => 'LY',
                'name' => 'Libya',
                'continent' => 'Africa',
                'dial_code' => '+218',
            ],
            [
                'code' => 'MA',
                'name' => 'Morocco',
                'continent' => 'Africa',
                'dial_code' => '+212',
            ],
            [
                'code' => 'MC',
                'name' => 'Monaco',
                'continent' => 'Europe',
                'dial_code' => '+377',
            ],
            [
                'code' => 'MD',
                'name' => 'Moldova',
                'continent' => 'Europe',
                'dial_code' => '+373',
            ],
            [
                'code' => 'ME',
                'name' => 'Montenegro',
                'continent' => 'Europe',
                'dial_code' => '+382',
            ],
            [
                'code' => 'MF',
                'name' => 'Saint Martin',
                'continent' => 'North America',
                'dial_code' => '+1599',
            ],
            [
                'code' => 'MG',
                'name' => 'Madagascar',
                'continent' => 'Africa',
                'dial_code' => '+261',
            ],
            [
                'code' => 'MH',
                'name' => 'Marshall Islands',
                'continent' => 'Oceania',
                'dial_code' => '+692',
            ],
            [
                'code' => 'MK',
                'name' => 'Macedonia',
                'continent' => 'Europe',
                'dial_code' => '+389',
            ],
            [
                'code' => 'ML',
                'name' => 'Mali',
                'continent' => 'Africa',
                'dial_code' => '+223',
            ],
            [
                'code' => 'MM',
                'name' => 'Myanmar',
                'continent' => 'Asia',
                'dial_code' => '+95',
            ],
            [
                'code' => 'MN',
                'name' => 'Mongolia',
                'continent' => 'Asia',
                'dial_code' => '+976',
            ],
            [
                'code' => 'MO',
                'name' => 'Macao',
                'continent' => 'Asia',
                'dial_code' => '+853',
            ],
            [
                'code' => 'MP',
                'name' => 'Northern Mariana Islands',
                'continent' => 'Oceania',
                'dial_code' => '+1670',
            ],
            [
                'code' => 'MQ',
                'name' => 'Martinique',
                'continent' => 'North America',
                'dial_code' => '+596',
            ],
            [
                'code' => 'MR',
                'name' => 'Mauritania',
                'continent' => 'Africa',
                'dial_code' => '+222',
            ],
            [
                'code' => 'MS',
                'name' => 'Montserrat',
                'continent' => 'North America',
                'dial_code' => '+1664',
            ],
            [
                'code' => 'MT',
                'name' => 'Malta',
                'continent' => 'Europe',
                'dial_code' => '+356',
            ],
            [
                'code' => 'MU',
                'name' => 'Mauritius',
                'continent' => 'Africa',
                'dial_code' => '+230',
            ],
            [
                'code' => 'MV',
                'name' => 'Maldives',
                'continent' => 'Asia',
                'dial_code' => '+960',
            ],
            [
                'code' => 'MW',
                'name' => 'Malawi',
                'continent' => 'Africa',
                'dial_code' => '+265',
            ],
            [
                'code' => 'MX',
                'name' => 'Mexico',
                'continent' => 'North America',
                'dial_code' => '+52',
            ],
            [
                'code' => 'MY',
                'name' => 'Malaysia',
                'continent' => 'Asia',
                'dial_code' => '+60',
            ],
            [
                'code' => 'MZ',
                'name' => 'Mozambique',
                'continent' => 'Africa',
                'dial_code' => '+258',
            ],
            [
                'code' => 'NA',
                'name' => 'Namibia',
                'continent' => 'Africa',
                'dial_code' => '+264',
            ],
            [
                'code' => 'NC',
                'name' => 'New Caledonia',
                'continent' => 'Oceania',
                'dial_code' => '+687',
            ],
            [
                'code' => 'NE',
                'name' => 'Niger',
                'continent' => 'Africa',
                'dial_code' => '+227',
            ],
            [
                'code' => 'NF',
                'name' => 'Norfolk Island',
                'continent' => 'Oceania',
                'dial_code' => '+672',
            ],
            [
                'code' => 'NG',
                'name' => 'Nigeria',
                'continent' => 'Africa',
                'dial_code' => '+234',
            ],
            [
                'code' => 'NI',
                'name' => 'Nicaragua',
                'continent' => 'North America',
                'dial_code' => '+505',
            ],
            [
                'code' => 'NL',
                'name' => 'Netherlands',
                'continent' => 'Europe',
                'dial_code' => '+31',
            ],
            [
                'code' => 'NO',
                'name' => 'Norway',
                'continent' => 'Europe',
                'dial_code' => '+47',
            ],
            [
                'code' => 'NP',
                'name' => 'Nepal',
                'continent' => 'Asia',
                'dial_code' => '+977',
            ],
            [
                'code' => 'NR',
                'name' => 'Nauru',
                'continent' => 'Oceania',
                'dial_code' => '+674',
            ],
            [
                'code' => 'NU',
                'name' => 'Niue',
                'continent' => 'Oceania',
                'dial_code' => '+683',
            ],
            [
                'code' => 'NZ',
                'name' => 'New Zealand',
                'continent' => 'Oceania',
                'dial_code' => '+64',
            ],
            [
                'code' => 'OM',
                'name' => 'Oman',
                'continent' => 'Asia',
                'dial_code' => '+968',
            ],
            [
                'code' => 'PA',
                'name' => 'Panama',
                'continent' => 'North America',
                'dial_code' => '+507',
            ],
            [
                'code' => 'PE',
                'name' => 'Peru',
                'continent' => 'South America',
                'dial_code' => '+51',
            ],
            [
                'code' => 'PF',
                'name' => 'French Polynesia',
                'continent' => 'Oceania',
                'dial_code' => '+689',
            ],
            [
                'code' => 'PG',
                'name' => 'Papua New Guinea',
                'continent' => 'Oceania',
                'dial_code' => '+675',
            ],
            [
                'code' => 'PH',
                'name' => 'Philippines',
                'continent' => 'Asia',
                'dial_code' => '+63',
            ],
            [
                'code' => 'PK',
                'name' => 'Pakistan',
                'continent' => 'Asia',
                'dial_code' => '+92',
            ],
            [
                'code' => 'PL',
                'name' => 'Poland',
                'continent' => 'Europe',
                'dial_code' => '+48',
            ],
            [
                'code' => 'PM',
                'name' => 'Saint Pierre and Miquelon',
                'continent' => 'North America',
                'dial_code' => '+508',
            ],
            [
                'code' => 'PN',
                'name' => 'Pitcairn Islands',
                'continent' => 'Oceania',
                'dial_code' => '+870',
            ],
            [
                'code' => 'PR',
                'name' => 'Puerto Rico',
                'continent' => 'North America',
                'dial_code' => '+1',
            ],
            [
                'code' => 'PS',
                'name' => 'Palestine',
                'continent' => 'Asia',
                'dial_code' => '+970',
            ],
            [
                'code' => 'PT',
                'name' => 'Portugal',
                'continent' => 'Europe',
                'dial_code' => '+351',
            ],
            [
                'code' => 'PW',
                'name' => 'Palau',
                'continent' => 'Oceania',
                'dial_code' => '+680',
            ],
            [
                'code' => 'PY',
                'name' => 'Paraguay',
                'continent' => 'South America',
                'dial_code' => '+595',
            ],
            [
                'code' => 'QA',
                'name' => 'Qatar',
                'continent' => 'Asia',
                'dial_code' => '+974',
            ],
            [
                'code' => 'RE',
                'name' => 'Réunion',
                'continent' => 'Africa',
                'dial_code' => '+262',
            ],
            [
                'code' => 'RO',
                'name' => 'Romania',
                'continent' => 'Europe',
                'dial_code' => '+40',
            ],
            [
                'code' => 'RS',
                'name' => 'Serbia',
                'continent' => 'Europe',
                'dial_code' => '+381',
            ],
            [
                'code' => 'RU',
                'name' => 'Russia',
                'continent' => 'Europe',
                'dial_code' => '+7',
            ],
            [
                'code' => 'RW',
                'name' => 'Rwanda',
                'continent' => 'Africa',
                'dial_code' => '+250',
            ],
            [
                'code' => 'SA',
                'name' => 'Saudi Arabia',
                'continent' => 'Asia',
                'dial_code' => '+966',
            ],
            [
                'code' => 'SB',
                'name' => 'Solomon Islands',
                'continent' => 'Oceania',
                'dial_code' => '+677',
            ],
            [
                'code' => 'SC',
                'name' => 'Seychelles',
                'continent' => 'Africa',
                'dial_code' => '+248',
            ],
            [
                'code' => 'SD',
                'name' => 'Sudan',
                'continent' => 'Africa',
                'dial_code' => '+249',
            ],
            [
                'code' => 'SE',
                'name' => 'Sweden',
                'continent' => 'Europe',
                'dial_code' => '+46',
            ],
            [
                'code' => 'SG',
                'name' => 'Singapore',
                'continent' => 'Asia',
                'dial_code' => '+65',
            ],
            [
                'code' => 'SH',
                'name' => 'Saint Helena',
                'continent' => 'Africa',
                'dial_code' => '+290',
            ],
            [
                'code' => 'SI',
                'name' => 'Slovenia',
                'continent' => 'Europe',
                'dial_code' => '+386',
            ],
            [
                'code' => 'SJ',
                'name' => 'Svalbard and Jan Mayen',
                'continent' => 'Europe',
                'dial_code' => '+47',
            ],
            [
                'code' => 'SK',
                'name' => 'Slovakia',
                'continent' => 'Europe',
                'dial_code' => '+421',
            ],
            [
                'code' => 'SL',
                'name' => 'Sierra Leone',
                'continent' => 'Africa',
                'dial_code' => '+232',
            ],
            [
                'code' => 'SM',
                'name' => 'San Marino',
                'continent' => 'Europe',
                'dial_code' => '+378',
            ],
            [
                'code' => 'SN',
                'name' => 'Senegal',
                'continent' => 'Africa',
                'dial_code' => '+221',
            ],
            [
                'code' => 'SO',
                'name' => 'Somalia',
                'continent' => 'Africa',
                'dial_code' => '+252',
            ],
            [
                'code' => 'SR',
                'name' => 'Suriname',
                'continent' => 'South America',
                'dial_code' => '+597',
            ],
            [
                'code' => 'SS',
                'name' => 'South Sudan',
                'continent' => 'Africa',
                'dial_code' => '+211',
            ],
            [
                'code' => 'ST',
                'name' => 'São Tomé and Príncipe',
                'continent' => 'Africa',
                'dial_code' => '+239',
            ],
            [
                'code' => 'SV',
                'name' => 'El Salvador',
                'continent' => 'North America',
                'dial_code' => '+503',
            ],
            [
                'code' => 'SX',
                'name' => 'Sint Maarten',
                'continent' => 'North America',
                'dial_code' => '+1',
            ],
            [
                'code' => 'SY',
                'name' => 'Syria',
                'continent' => 'Asia',
                'dial_code' => '+963',
            ],
            [
                'code' => 'SZ',
                'name' => 'Swaziland',
                'continent' => 'Africa',
                'dial_code' => '+268',
            ],
            [
                'code' => 'TC',
                'name' => 'Turks and Caicos Islands',
                'continent' => 'North America',
                'dial_code' => '+1649',
            ],
            [
                'code' => 'TD',
                'name' => 'Chad',
                'continent' => 'Africa',
                'dial_code' => '+235',
            ],
            [
                'code' => 'TF',
                'name' => 'French Southern Territories',
                'continent' => 'Antarctica',
                'dial_code' => '+262',
            ],
            [
                'code' => 'TG',
                'name' => 'Togo',
                'continent' => 'Africa',
                'dial_code' => '+228',
            ],
            [
                'code' => 'TH',
                'name' => 'Thailand',
                'continent' => 'Asia',
                'dial_code' => '+66',
            ],
            [
                'code' => 'TJ',
                'name' => 'Tajikistan',
                'continent' => 'Asia',
                'dial_code' => '+992',
            ],
            [
                'code' => 'TK',
                'name' => 'Tokelau',
                'continent' => 'Oceania',
                'dial_code' => '+690',
            ],
            [
                'code' => 'TL',
                'name' => 'Timor-Leste',
                'continent' => 'Oceania',
                'dial_code' => '+670',
            ],
            [
                'code' => 'TM',
                'name' => 'Turkmenistan',
                'continent' => 'Asia',
                'dial_code' => '+993',
            ],
            [
                'code' => 'TN',
                'name' => 'Tunisia',
                'continent' => 'Africa',
                'dial_code' => '+216',
            ],
            [
                'code' => 'TO',
                'name' => 'Tonga',
                'continent' => 'Oceania',
                'dial_code' => '+676',
            ],
            [
                'code' => 'TR',
                'name' => 'Turkey',
                'continent' => 'Asia',
                'dial_code' => '+90',
            ],
            [
                'code' => 'TT',
                'name' => 'Trinidad and Tobago',
                'continent' => 'North America',
                'dial_code' => '+1868',
            ],
            [
                'code' => 'TV',
                'name' => 'Tuvalu',
                'continent' => 'Oceania',
                'dial_code' => '+688',
            ],
            [
                'code' => 'TW',
                'name' => 'Taiwan',
                'continent' => 'Asia',
                'dial_code' => '+886',
            ],
            [
                'code' => 'TZ',
                'name' => 'Tanzania',
                'continent' => 'Africa',
                'dial_code' => '+255',
            ],
            [
                'code' => 'UA',
                'name' => 'Ukraine',
                'continent' => 'Europe',
                'dial_code' => '+380',
            ],
            [
                'code' => 'UG',
                'name' => 'Uganda',
                'continent' => 'Africa',
                'dial_code' => '+256',
            ],
            [
                'code' => 'UM',
                'name' => 'U.S. Minor Outlying Islands',
                'continent' => 'Oceania',
                'dial_code' => '+1',
            ],
            [
                'code' => 'US',
                'name' => 'United States',
                'continent' => 'North America',
                'dial_code' => '+1',
            ],
            [
                'code' => 'UY',
                'name' => 'Uruguay',
                'continent' => 'South America',
                'dial_code' => '+598',
            ],
            [
                'code' => 'UZ',
                'name' => 'Uzbekistan',
                'continent' => 'Asia',
                'dial_code' => '+998',
            ],
            [
                'code' => 'VA',
                'name' => 'Vatican City',
                'continent' => 'Europe',
                'dial_code' => '+379',
            ],
            [
                'code' => 'VC',
                'name' => 'Saint Vincent and the Grenadines',
                'continent' => 'North America',
                'dial_code' => '+1784',
            ],
            [
                'code' => 'VE',
                'name' => 'Venezuela',
                'continent' => 'South America',
                'dial_code' => '+58',
            ],
            [
                'code' => 'VG',
                'name' => 'Virgin Islands (British)',
                'continent' => 'North America',
                'dial_code' => '+1284',
            ],
            [
                'code' => 'VI',
                'name' => 'Virgin Islands (U.S.)',
                'continent' => 'North America',
                'dial_code' => '+1340',
            ],
            [
                'code' => 'VN',
                'name' => 'Viet Nam',
                'continent' => 'Asia',
                'dial_code' => '+84',
            ],
            [
                'code' => 'VU',
                'name' => 'Vanuatu',
                'continent' => 'Oceania',
                'dial_code' => '+678',
            ],
            [
                'code' => 'WF',
                'name' => 'Wallis and Futuna',
                'continent' => 'Oceania',
                'dial_code' => '+681',
            ],
            [
                'code' => 'WS',
                'name' => 'Samoa',
                'continent' => 'Oceania',
                'dial_code' => '+685',
            ],
            [
                'code' => 'XK',
                'name' => 'Kosovo',
                'continent' => 'Europe',
                'dial_code' => '+381',
            ],
            [
                'code' => 'YE',
                'name' => 'Yemen',
                'continent' => 'Asia',
                'dial_code' => '+967',
            ],
            [
                'code' => 'YT',
                'name' => 'Mayotte',
                'continent' => 'Africa',
                'dial_code' => '+262',
            ],
            [
                'code' => 'ZA',
                'name' => 'South Africa',
                'continent' => 'Africa',
                'dial_code' => '+27',
            ],
            [
                'code' => 'ZM',
                'name' => 'Zambia',
                'continent' => 'Africa',
                'dial_code' => '+260',
            ],
            [
                'code' => 'ZW',
                'name' => 'Zimbabwe',
                'continent' => 'Africa',
                'dial_code' => '+263',
            ],
        ]);

        DB::table((new Country())->getTable())
            ->insert($countries);
    }

    public function down(): void
    {
        // 1 way
    }
};
